### ISSUE TITLE
tar: ./var/lib/lxd/unix.socket: socket ignored

### ISSUE THREAD

**Issue by NirajVisana** [thenickdude/snap-to-s3#13]
I am attaching SS here, I tried with Ubuntu and Linux AMI both the same error so I want to know it is uploading the whole ebs or not, and how to avoid this error. 

Screenshot
https://ibb.co/yR7f4gs

**Comment by thenickdude** [comment]
That's fine, that's just `tar` telling you that it is unable to represent an open socket file in the tar, so it's dropping it. This is because it is meaningless to unpack a socket file from a tar, since it wouldn't recreate the active connection that the socket file represented.

Your daemons (like `lxd` here) recreate these Unix socket files during their startup.

**Comment by NirajVisana** [comment]
@thenickdude it stopped at 84% so whole back up was taken, right?

**Comment by thenickdude** [comment]
It didn't stop at 84%, it just creates a new progress bar on the screen if any message gets printed inbetween (you'll see the same thing happen if you resize the terminal window). The backup completed 100%, which you can see on the subsequent lines.

How did the validation go (shown as still in progress in your snapshot there)? That redownloads the tar from S3 and compares the hash of all the files in that tar against the files on the local EBS volume, and so double checks that all hashed files were backed up successfully. If validation completes successfully, a "validated" tag will be added to snapshot with the key name "snap-to-s3" to confirm it (and it gets printed to the console).

**Comment by NirajVisana** [comment]
Hello sorry for progress in between image, this is how the whole process goes.

https://ibb.co/9GKM1TW
