### ISSUE TITLE
FS failed... I have Windows snapshots 

### ISSUE THREAD

**Issue by olevenkov-s** [thenickdude/snap-to-s3#4]
[snap-093de0f5e3d376b64] Migrating snap-093de0f5e3d376b64 to S3
[snap-093de0f5e3d376b64] Tagging snapshot with "migrating"...
[snap-093de0f5e3d376b64] Creating temporary EBS volume of type "standard" from snapshot
[snap-093de0f5e3d376b64] Attaching vol-02af295d4171dc450 to this instance (i-0940490a053bac25d) at /dev/sdo...
[snap-093de0f5e3d376b64] Waiting for vol-02af295d4171dc450's partitions to become visible to the operating system...
[snap-093de0f5e3d376b64] 2 partitions to upload
[snap-093de0f5e3d376b64] 
[snap-093de0f5e3d376b64] Uploading partition 1 of 2...
[snap-093de0f5e3d376b64] Mounting /dev/xvdo1 at /mnt/snap-093de0f5e3d376b64-1...
[snap-093de0f5e3d376b64] An error occurred, tagging snapshot with "migrate" so it can be retried later
[snap-093de0f5e3d376b64] mount --source /dev/xvdo1 --target /mnt/snap-093de0f5e3d376b64-1 --read-only failed:  mount: wrong fs type, bad option, bad superblock on /dev/xvdo1,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

Terminating due to fatal errors.

**Comment by thenickdude** [comment]
The instance you're using needs to be able to mount the filesystems being backed up using the "mount" command, the log output here shows that that's failing. Maybe you need to install an NTFS package?

Otherwise, you can pass the `--dd` option to snap-to-s3 and it'll create a raw image of the entire disk rather than backing up files in a tar (this will result in larger backups if your disk has a lot of empty space / deleted files).
